server:
  port: 80
  servlet:
    context-path: /
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cities
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create
