server:
  port: 8081
  servlet:
    context-path: /list-app
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cities
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger